CC = g++
SRC_FILES = src/*.cpp
BIN_NAME = CG
COMPILER_FLAGS = -w -std=c++11
LINKER_FLAGS = -lSDL2
INCLUDE_FOLDER = include

all: $(SRC_FILES)
	$(CC) $(SRC_FILES) $(COMPILER_FLAGS) $(LINKER_FLAGS) -I$(INCLUDE_FOLDER) -o $(BIN_NAME)
